name: Build and Deploy

on:
  push:
    branches:
      - KillYourMaster
  issues:
    types: [opened, edited, reopened, closed, deleted, labeled, unlabeled]

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Cache Node dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.cache-name }}-
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Build Microblog
        uses: herschel666/microblog-action@beta
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          url: 'https://ekblog.de'
          lang: 'de'
          title: 'ek|blog'
          description: 'Gemischter Un-, Fein- & Irrsinn'
          date-format: 'd.M.yyyy'
          label: 'blawg'
          i18n.posts: 'Artikel'
          i18n.prev: 'vorherige Artikel'
          i18n.next: 'nächste Artikel'
          custom-javascript: 'dist/bundle.js'

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: '_site'
          production-branch: KillYourMaster
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from microblog action'
          enable-pull-request-comment: false
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
